### ISSUE TITLE
Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by barik** [dockerizeme/dockerizeme#1]
I couldn't get `dockerizeme` to run (also the instructions don't specify running `npm install` after cloning).

```
c:\repos\dockerizeme (master -> origin) (dockerizeme@1.0.0)
λ npm install
npm WARN dockerizeme@1.0.0 No repository field.

audited 142 packages in 0.852s
found 3 vulnerabilities (2 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

c:\repos\dockerizeme (master -> origin) (dockerizeme@1.0.0)
λ npm run dockerizeme

> dockerizeme@1.0.0 dockerizeme c:\repos\dockerizeme
> node src/bin.js

2019-06-15T14:44:17.190Z - error:  Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at spawn (child_process.js:539:9)
    at Object.execFile (child_process.js:221:17)
    at c:\repos\dockerizeme\src\language-strategy.js:179:70
    at tryCatcher (c:\repos\dockerizeme\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (c:\repos\dockerizeme\node_modules\bluebird\js\release\promise.js:180:30)
    at PythonStrategy.parsePackageDependencies (c:\repos\dockerizeme\src\language-strategy.js:179:37)
    at c:\repos\dockerizeme\src\language-strategy.js:217:35
    at tryCatcher (c:\repos\dockerizeme\node_modules\bluebird\js\release\util.js:16:23)
    at c:\repos\dockerizeme\node_modules\bluebird\js\release\using.js:185:26
    at tryCatcher (c:\repos\dockerizeme\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\repos\dockerizeme\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (c:\repos\dockerizeme\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (c:\repos\dockerizeme\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (c:\repos\dockerizeme\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (c:\repos\dockerizeme\node_modules\bluebird\js\release\promise.js:638:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dockerizeme@1.0.0 dockerizeme: `node src/bin.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dockerizeme@1.0.0 dockerizeme script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Using Windows.

node 12.3.1
npm 6.9.0

**Comment by dockerizeme** [comment]
Sorry for the delayed response. The documentation could use some work.

Looking at the stack trace, the process is failing during the parsing phase. This likely indicates a problem with the local Python installation (which is handled by Python), a malformed or missing Python script to parse, or a bug in the parsing script.

I recommend using the provided Vagrant file or [virtual machine image](https://github.com/dockerizeme/dockerizeme/releases/download/ICSE2019-ArtifactEvaluation-Zenodo/dockerizeme.ova) to configure a runtime environment.

**Comment by dockerizeme** [comment]
Closing for inactivity. Please let us know if you have any additional issues getting DockerizeMe running.
