### ISSUE TITLE
How to install dockerizeme locally and use it for a Python script

### ISSUE THREAD

**Issue by Jarvx** [dockerizeme/dockerizeme#4]
I found this project really interesting but I am a bit confused about how to set up it propers.  What steps should I follow  to make it work. After tried all the commands in the README, I used the below command.
`
npm run dockerizeme --verbose examples/dashtable/snippet.py 

`
But the results are :

`
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'run',
npm verb cli   'dockerizeme',
npm verb cli   '--verbose',
npm verb cli   'examples/dashtable/snippet.py' ]
npm info using npm@3.5.2
npm info using node@v8.10.0
npm verb run-script [ 'predockerizeme', 'dockerizeme', 'postdockerizeme' ]
npm info lifecycle dockerizeme@1.0.0~predockerizeme: dockerizeme@1.0.0
npm info lifecycle dockerizeme@1.0.0~dockerizeme: dockerizeme@1.0.0

> dockerizeme@1.0.0 dockerizeme /home/jiawei/pysoot/dockerizeme
> node src/bin.js "examples/dashtable/snippet.py"

module.js:549
    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jiawei/pysoot/dockerizeme/src/bin.js:11:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

`

**Comment by dockerizeme** [comment]
It looks like you're missing the required Node.js dependencies. You can install them with

```
$ npm install
```

We also provide a VM image in our [artifact release](http://github.com/dockerizeme/dockerizeme/releases/tag/ICSE2019-ArtifactEvaluation) that has everything installed and ready to go. I think the default username/password is vagrant/vagrant to match the vagrant configuration.

I also recommend checking out [V2](https://github.com/v2-project/v2), a successor to this project with better handling for dependency versions.
